# Generated by Django 4.2.13 on 2024-06-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Berth",
            fields=[
                (
                    "berth_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="泊位编号",
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="状态")),
                ("area", models.CharField(max_length=50, verbose_name="区域")),
            ],
            options={
                "verbose_name": "泊位",
                "verbose_name_plural": "泊位",
            },
        ),
        migrations.CreateModel(
            name="OceanCurrent",
            fields=[
                (
                    "ocean_current_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="洋流编号",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="记录日期时间")),
                (
                    "silt_condition",
                    models.CharField(max_length=100, verbose_name="淤沙状态"),
                ),
                (
                    "depth",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="深度"
                    ),
                ),
            ],
            options={
                "verbose_name": "洋流",
                "verbose_name_plural": "洋流",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "service_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="服务编号",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="服务类型")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="费用"
                    ),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
            },
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户账号",
                    ),
                ),
                (
                    "ship_id",
                    models.CharField(
                        default="Null", max_length=50, verbose_name="船舶编号"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="Null", max_length=100, verbose_name="船舶类型"
                    ),
                ),
                ("contact_info", models.CharField(max_length=255, verbose_name="联系方式")),
                (
                    "draft_depth",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="吃水深度"
                    ),
                ),
                (
                    "login_status",
                    models.BooleanField(default=False, verbose_name="登录状态"),
                ),
                (
                    "pwd",
                    models.CharField(
                        default="123456", max_length=20, verbose_name="密码"
                    ),
                ),
            ],
            options={
                "verbose_name": "船舶",
                "verbose_name_plural": "船舶",
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "weather_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="天气编号",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="记录日期时间")),
                (
                    "warning_level",
                    models.CharField(
                        choices=[("normal", "正常"), ("alert", "警告"), ("danger", "危险")],
                        max_length=10,
                        verbose_name="预警级别",
                    ),
                ),
                ("description", models.TextField(verbose_name="天气描述")),
            ],
            options={
                "verbose_name": "天气",
                "verbose_name_plural": "天气",
            },
        ),
    ]
