# Generated by Django 4.2.13 on 2024-06-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PortModels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="rainfall",
            field=models.DecimalField(
                decimal_places=2, default=200, max_digits=10, verbose_name="降雨量"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weather",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, default=25, max_digits=10, verbose_name="气温"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ship",
            name="user_id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="用户主键"
            ),
        ),
    ]
