# Generated by Django 4.2.13 on 2024-06-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PortModels", "0002_weather_rainfall_weather_temperature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordBerth",
            fields=[
                (
                    "record_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="记录主键",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, verbose_name="用户主键")),
                (
                    "ship_id",
                    models.CharField(
                        default="Null", max_length=50, verbose_name="船舶编号"
                    ),
                ),
                ("berth_id", models.CharField(max_length=50, verbose_name="泊位编号")),
                ("in_time", models.DateTimeField(verbose_name="入港时间")),
                ("out_time", models.DateTimeField(verbose_name="离港时间")),
                (
                    "berth_state",
                    models.BooleanField(default=False, verbose_name="当前停放状态"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordServe",
            fields=[
                (
                    "record_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="记录主键",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="消费时间")),
                ("user_id", models.CharField(max_length=50, verbose_name="用户主键")),
                ("service_id", models.CharField(max_length=50, verbose_name="服务编号")),
            ],
        ),
    ]
