# Generated by Django 4.2.13 on 2024-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PortModels", "0003_recordberth_recordserve"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordServer",
            fields=[
                (
                    "record_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="记录主键",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="消费时间")),
                ("user_id", models.CharField(max_length=50, verbose_name="用户主键")),
                (
                    "server_details",
                    models.CharField(default="无", max_length=100, verbose_name="服务描述"),
                ),
                (
                    "server_info",
                    models.CharField(default="无", max_length=50, verbose_name="服务简介"),
                ),
                (
                    "contact_info",
                    models.CharField(default="0", max_length=50, verbose_name="联系方式"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="消费金额"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RecordServe",
        ),
        migrations.RemoveField(
            model_name="service",
            name="type",
        ),
        migrations.AddField(
            model_name="service",
            name="info",
            field=models.CharField(default=0, max_length=100, verbose_name="服务描述"),
            preserve_default=False,
        ),
    ]
