# Generated by Django 4.2.13 on 2024-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "PortModels",
            "0004_recordserver_delete_recordserve_remove_service_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordserver",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="消费金额"
            ),
        ),
    ]
